### PR TITLE
Adding pages from old wiki

### PR DESCRIPTION
**Pull request by csev1755**
Added some content from the old wiki to the new one. Still learning the ropes of GitHub, please let me know if these should all be separate requests.

### CODE REVIEW

**Review by FlyRouter — COMMENTED** [review]
Unfortunately, we cannot accept this PR, as some of the information is outdated and needs to be corrected.
Please submit each file separately for review.
Thank you for your efforts.

**Comment by IhsenBouallegue** [comment]
@flyrouter what information exactly? it's hard to know when we don't have deep technical knowledge. Please write a review using github to mark the outdated parts

**Comment by flyrouter** [comment]
Good day
I wrote above what needs to be done first.
I have the utmost respect for every work and enthusiast, but we need rules, we have already discussed this.
So, the basic rules:
- we need a page indicating a uniform style for the design of headings, sections and lines with code and other designs when transferring articles (I mean the ##, ``` and other signs in Markdown), the style must be uniform
- please format each article transfer as a separate PR, no need to transfer 2-3 or many articles at once. Yes, this is routine and tedious work, what can you do.
- please separate menu corrections and article transfers into separate PRs, no need to do this at once, it is bad for understanding. First, articles are transferred, and then they are added to the menu. Or, in extreme cases, an article + one line of edits in the menu.
- after transferring articles from Wiki to Docs, or better yet, simultaneously, it is advisable to open a PR in Wiki, deleting information and specifying a link to the new path in Docs.

The current situation requires reviewing all content by images, organizing into directories and sections, since some information will be lost in the current transfer.

Everything I wrote above is an ideal wish and is not criticism, but you need to understand that only collective work on transferring information will give results. It will be very difficult for one person or he must be motivated. We can offer a small financial reward and can send equipment as a gift, but we need to somehow make sure that a person or a group of people are ready to start and bring the matter to the end. There is no other way here, unfortunately.

At the same time, I will not impose any vetoes and if someone is ready to take the process into their own hands, that would be great.

Thank you for understanding.

**Comment by csev1755** [comment]
Thank you for the detailed guidelines, I will go ahead and close this until I have new PRs to open properly

**Pull request closed without merging**
