### PR TITLE
Update roadmap.mdx

### PR DESCRIPTION
**Pull request by FlyRouter**

### CODE REVIEW

**Comment by IhsenBouallegue** [comment]
Is this a test?

**Comment by FlyRouter** [comment]
This is a change in direction of the roadmap, the most recent at the top.
Well, a couple of comments, in the future I want to add several lines per point on the roadmap, please suggest some solution for quickly launching beautiful formatting, something like this

* features number one
* feature number two
* features number three

**Comment by IhsenBouallegue** [comment]
@FlyRouter it has been added. And I named them goals. Better close this PR and open a new one to avoid headaches resolving conflicts.

> * features number one
> 
> * feature number two
> 
> * features number three

**Comment by FlyRouter** [comment]
Thank you

**Pull request closed without merging**
